version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: hoodi
        P2P_TCP_PORT: 14603
        P2P_UDP_PORT: 14603
    ports:
      - 14603:14603/tcp
      - 14603:14603/udp
    environment:
      CORSDOMAIN: "*"
  validator:
    build:
      args:
        NETWORK: hoodi
        BEACON_RPC_PROVIDER: "beacon-chain.prysm-hoodi.dappnode:4000"
        BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.prysm-hoodi.dappnode:3500"
