version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: lukso
        P2P_TCP_PORT: 12603
        P2P_UDP_PORT: 12603
        UPSTREAM_VERSION: v5.0.4
    ports:
      - 12603:12603/tcp
      - 12603:12603/udp
    environment:
      CORSDOMAIN: "*"
      MIN_SYNC_PEERS: "1"
      MAX_PEERS: "70"
      SUBSCRIBE_ALL_SUBNETS: "false"
  validator:
    build:
      args:
        UPSTREAM_VERSION: v5.0.4
        NETWORK: lukso
        BEACON_RPC_PROVIDER: "beacon-chain.prysm-lukso.dappnode:4000"
        BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.prysm-lukso.dappnode:3500"
